//
// Created on 08/11/2017.
//

#ifndef NUMKINCH_CONSTANTS_H
#define NUMKINCH_CONSTANTS_H

enum GUIConstants
{
    NB_PLAYERS = 4,

    WINDOW_WIDTH = 1280,

    WINDOW_HEIGHT = 1024,

    BUTTON_WIDTH = 300,

    BUTTON_HEIGHT = 150,

    BUTTON_BIG_CARD_WIDTH = 125,

    BUTTON_BIG_CARD_HEIGHT = 62,

    CHAR_CARD_WIDTH = 200,

    CHAR_CARD_HEIGHT = 320,

    CHAR_CARD_MARGIN_SIDE = (WINDOW_WIDTH - 4 * CHAR_CARD_WIDTH) / 2,

    CHAR_CARD_MARGIN_TOP = 320,

    STAT_CARD_WIDTH = 310,

    STAT_CARD_HEIGHT = 162,

    CARD_WIDTH = 75,

    CARD_HEIGHT = 120,

    CARD_MARGIN_SIDE = 100,

    CARD_MARGIN_TOP = 350,

    BIG_CARD_WIDTH = 350,

    BIG_CARD_HEIGHT = 600,

    BIG_CARD_MARGIN_SIDE = 600,

    BIG_CARD_MARGIN_TOP = 350,

    ENTITY_IMAGE_WIDTH = 280,

    ENTITY_IMAGE_HEIGHT = 180,

    ENTITY_IMAGE_MARGIN_SIDE = (BIG_CARD_WIDTH - ENTITY_IMAGE_WIDTH) / 2,

    ENTITY_IMAGE_MARGIN_TOP = 100
};

#endif //NUMKINCH_CONSTANTS_H
