//
// Created on 08/11/2017.
//

#ifndef NUMKINCH_PLAYER_LOGIC_CONSTANTS_H
#define NUMKINCH_PLAYER_LOGIC_CONSTANTS_H


enum PlayerLogicConstants
{
    ATTACK_VALUE = 10,
    ATTACK_MAX_VALUE = 40,
    ATTACK_BONUS = 10,
    ATTACK_MAX_BONUS = 40,

    DEFENSE_VALUE = 5,
    DEFENSE_MAX_VALUE = 30,
    DEFENSE_BONUS = 5,
    DEFENSE_MAX_BONUS = 30,

    AGILITY_VALUE = 10,
    AGILITY_MAX_VALUE = 40,
    AGILITY_BONUS = 10,
    AGILITY_MAX_BONUS = 40,

    LIFE_VALUE = 100,
    LIFE_MAX_VALUE = 200,
    LIFE_BONUS = 20,
    LIFE_MAX_BONUS = 100,
    LIFE_INCREASE = 5,
};

#endif //NUMKINCH_PLAYER_LOGIC_CONSTANTS_H

